### ISSUE TITLE
how to get callback when this finishes? 

### ISSUE THREAD

**Issue by johndpope** [devtud/aerender#2]
It seems this line will just skip over....
 asyncio.run(coro)

is there an exit hook?
I'm currently using zmq to great effect - maybe I'll have to mangle the script to shoot out a message.

import asyncio
import zmq
import sys
from pathlib import Path
import os
from aerender import AERenderWrapper

asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
port = 5555

if __name__ == '__main__':
    context = zmq.Context()
    socket = context.socket(zmq.SUB)
    socket.setsockopt(zmq.SUBSCRIBE, b'')
    socket.connect('tcp://192.168.1.110:%i' % port)
      
    while True:
        msg = socket.recv_pyobj()
        print("%s:" % msg)
        if msg['event'] == 'startProcessing' :
            AERENDER_FULLPATH = Path('C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe')
            aerender = AERenderWrapper(exe_path=AERENDER_FULLPATH)
            coro = aerender.run(
                project_path=Path("C:\\Users\\jp\\Documents\\gitWorkspace\\coop\\aws-swf-python\\render\\profile.aep"),
                comp_name='render',
                output_path=Path('C:\\Users\\jp\\Documents\\gitWorkspace\\coop\\aws-swf-python\\render\\profile.mov'),
            )
            asyncio.run(coro)

**Comment by devtud** [comment]
What is certain from the start is that this project may be improved regarding logging, usability and handling errors.

What version of Adobe After Effects are you using?

Now, if the coroutine finishes immediately and it doesn't produce the video output, most probably the aerender.exe process gets an error. You can run the process directly in power shell to visualize the log lines and figure the problem out. You can paste the logs here maybe it's a problem not handled by the python wrapper.

In PowerShell you should be able to run it with:
```ps
& 'C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe' -project 'C:\\Users\\jp\\Documents\\gitWorkspace\\coop\\aws-swf-python\\render\\profile.aep'  -comp render -output 'C:\\Users\\jp\\Documents\\gitWorkspace\\coop\\aws-swf-python\\render\\profile.mov'
```

**Comment by johndpope** [comment]
It runs fine - and files created - but I need to notify a workflow process to upload it. I need a hook in at this point.
 asyncio.run(coro)
// or may I can just add it below this line, right? but this line is non blocking...... I'll try.

**Comment by devtud** [comment]
That line _is_ blocking and adding a `print("DONE")` after it should be just fine. If you encounter any problem maybe I can help.

**Comment by johndpope** [comment]
if it errors - that would be useful to know. thanks

**Comment by devtud** [comment]
@johndpope You can expect one of the errors from https://github.com/devtud/aerender/blob/master/aerender/exceptions.py to be raised if something happens. However, I'm sure that not all of the cases are covered. For basic usage as the one you showed you should be covered.
